# Generated by Django 6.0.2 on 2026-02-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_role_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
