# Generated by Django 6.0.2 on 2026-02-17 09:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('account_type', models.CharField(blank=True, default='mpesa', max_length=20, verbose_name='Account Type')),
                ('mpesa_phone_number', models.CharField(blank=True, max_length=15, verbose_name='Phone number')),
                ('current_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Current balance')),
                ('minimum_threshold', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Minimum Threshold')),
            ],
            options={
                'verbose_name': 'PettyCash account',
                'verbose_name_plural': 'PettyCash accounts',
                'db_table': 'pettycash_account',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('expense_type', models.CharField(choices=[('reimbursement', 'Reimbursement'), ('disbursement', 'Disbursement')], default='reimbursement', max_length=20, verbose_name='Expense Type')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('mpesa_phone', models.CharField(blank=True, max_length=20, verbose_name='M-Pesa Phone')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('receipt_url', models.JSONField(blank=True, default=list, verbose_name='Receipt URLs')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_expense_requests', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests', to='base.category', verbose_name='Category')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_request', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Expense Request',
                'verbose_name_plural': 'Expense Requests',
                'db_table': 'expense_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopUpRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='Reason')),
                ('approved_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_topups', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('pettycash_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topup_requests', to='finance.pettycashaccount', verbose_name='Petty Cash Account')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_topups', to=settings.AUTH_USER_MODEL, verbose_name='Requested by')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topup_requests', to='base.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Top-up Request',
                'verbose_name_plural': 'TopUp Requests',
                'db_table': 'topup_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
