# Generated by Django 6.0.2 on 2026-02-17 11:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_status_table'),
        ('department', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserequest',
            name='decision_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Decision at'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_expense_requests', to=settings.AUTH_USER_MODEL, verbose_name='Decision by'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests', to='department.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests', to='base.status', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='topuprequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='topuprequest',
            name='is_auto_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='pettycashaccount',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Current balance'),
        ),
        migrations.AlterField(
            model_name='pettycashaccount',
            name='minimum_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Minimum Threshold'),
        ),
        migrations.CreateModel(
            name='DisbursementReconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved at')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Amount')),
                ('reconciled_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Reconciled Amount')),
                ('surplus_returned', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Surplus Returned')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_disbursement_reconciliations', to=settings.AUTH_USER_MODEL, verbose_name='Approved by')),
                ('expense_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_reconciliation', to='finance.expenserequest', verbose_name='Expense Request')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_reconciliations', to='base.status', verbose_name='Status')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_disbursement_reconciliations', to=settings.AUTH_USER_MODEL, verbose_name='Submitted by')),
            ],
            options={
                'verbose_name': 'Disbursement Reconciliation',
                'verbose_name_plural': 'Disbursement Reconciliations',
                'db_table': 'disbursement_reconciliations',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
