# Generated by Django 6.0.2 on 2026-02-21 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_expenserequest_decision_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserequest',
            name='decision_at',
        ),
        migrations.RemoveField(
            model_name='expenserequest',
            name='decision_by',
        ),
        migrations.RemoveField(
            model_name='expenserequest',
            name='department',
        ),
    ]
