# Generated by Django 6.0.2 on 2026-02-21 14:08

import django.db.models.deletion
import finance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_status_table'),
        ('finance', '0003_remove_expenserequest_decision_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequest',
            name='category',
            field=models.ForeignKey(default=finance.models.get_default_expense_category, on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests', to='base.category', verbose_name='Category'),
        ),
    ]
