# Generated by Django 6.0.2 on 2026-02-21 14:38

import django.db.models.deletion
import finance.default
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_status_table'),
        ('finance', '0004_alter_expenserequest_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, default=finance.default.get_default_finance_officer, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_expense_requests', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='expenserequest',
            name='status',
            field=models.ForeignKey(blank=True, default=finance.default.get_default_pending_status, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests', to='base.status', verbose_name='Status'),
        ),
    ]
