# Generated by Django 6.0.2 on 2026-02-22 14:38

import django.db.models.deletion
import finance.default
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_category_is_active_status_is_active'),
        ('finance', '0006_disbursementreconciliation_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuprequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_topups', to=settings.AUTH_USER_MODEL, verbose_name='Approved by'),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='status',
            field=models.ForeignKey(default=finance.default.get_default_pending_status, on_delete=django.db.models.deletion.PROTECT, related_name='topup_requests', to='base.status', verbose_name='Status'),
        ),
    ]
