# Generated by Django 6.0.2 on 2026-02-22 18:48

import django.db.models.deletion
import finance.default
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0007_notifications_is_active_transactionlogbase_is_active'),
        ('finance', '0007_alter_topuprequest_approved_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topuprequest',
            old_name='approved_by',
            new_name='decision_by',
        ),
        migrations.RemoveField(
            model_name='topuprequest',
            name='reason',
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='event_type',
            field=models.ForeignKey(blank=True, default=finance.default.get_default_expense_submitted_event, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_requests', to='audit.eventtypes', verbose_name='Event Type'),
        ),
        migrations.AddField(
            model_name='topuprequest',
            name='decision_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Decision Reason'),
        ),
        migrations.AddField(
            model_name='topuprequest',
            name='event_type',
            field=models.ForeignKey(blank=True, default=finance.default.get_default_topup_requested_event, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topup_requests', to='audit.eventtypes', verbose_name='Event Type'),
        ),
        migrations.AddField(
            model_name='topuprequest',
            name='request_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Request Reason'),
        ),
    ]
