# Generated by Django 6.0.2 on 2026-02-24 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_rename_approved_by_topuprequest_decision_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserequest',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_expense_requests', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
    ]
