# Generated by Django 6.0.2 on 2026-02-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_expenserequest_assigned_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserequest',
            name='assigned_to',
        ),
    ]
