# Generated by Django 6.0.2 on 2026-02-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_remove_expenserequest_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topuprequest',
            name='request_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Request Reason'),
        ),
    ]
