# Generated by Django 6.0.2 on 2026-02-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_topuprequest_request_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenserequest',
            name='receipt_url',
        ),
        migrations.AddField(
            model_name='disbursementreconciliation',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='reconciliation_receipts/%Y/%m/%d/', verbose_name='Receipt'),
        ),
        migrations.AddField(
            model_name='expenserequest',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/%d/', verbose_name='Receipt'),
        ),
    ]
