# Generated by Django 6.0.2 on 2026-02-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_remove_expenserequest_receipt_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disbursementreconciliation',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='disbursementreconciliation',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='disbursementreconciliation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='disbursementreconciliation',
            name='surplus_returned',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Surplus Returned'),
        ),
    ]
