# Generated by Django 6.0.2 on 2026-03-17 08:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_remove_disbursementreconciliation_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenserequest',
            name='receipt',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Receipt'),
        ),
    ]
