# Generated by Django 6.0.2 on 2026-03-17 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_expenserequest_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransactionCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Amount')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maximum Amount')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Transaction Cost')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction Cost',
                'verbose_name_plural': 'M-Pesa Transaction Costs',
                'db_table': 'mpesa_transaction_costs',
                'ordering': ['min_amount'],
            },
        ),
    ]
