# Generated by Django 6.0.2 on 2026-03-23 12:14

import cloudinary.models
import django.db.models.deletion
import finance.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_category_is_active_status_is_active'),
        ('finance', '0015_mpesatransactioncost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('max_loan_amount', models.DecimalField(decimal_places=2, default=10000, max_digits=10, verbose_name='Maximum Loan Amount (KES)')),
            ],
            options={
                'verbose_name': 'Loan Configuration',
                'db_table': 'loan_config',
            },
        ),
        migrations.AlterField(
            model_name='disbursementreconciliation',
            name='receipt',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Receipt'),
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('repaid_at', models.DateTimeField(blank=True, null=True, verbose_name='Repaid At')),
                ('decision_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Decision Reason')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('decision_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Decision By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_requests', to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
                ('status', models.ForeignKey(default=finance.models.get_default_pending_status, on_delete=django.db.models.deletion.PROTECT, related_name='loan_requests', to='base.status', verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Loan Request',
                'verbose_name_plural': 'Loan Requests',
                'db_table': 'loan_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
