# Generated by Django 6.0.2 on 2026-04-02 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_loanconfig_alter_disbursementreconciliation_receipt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='decision_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Decision By'),
        ),
    ]
