# Generated by Django 6.0.2 on 2026-04-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_alter_loanrequest_decision_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='phone_number',
            field=models.CharField(blank=True, null=True, verbose_name='Phone Number'),
        ),
    ]
