# Generated by Django 6.0.2 on 2026-02-17 06:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_alter_status_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Event Category',
                'verbose_name_plural': 'Event Categories',
            },
        ),
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Description')),
                ('status_code', models.CharField(blank=True, max_length=30, verbose_name='Status Code')),
                ('is_active', models.BooleanField(default=True)),
                ('event_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_types', to='audit.eventcategory', verbose_name='Event Category')),
            ],
            options={
                'verbose_name': 'Event Type',
                'verbose_name_plural': 'Event Types',
            },
        ),
        migrations.CreateModel(
            name='TransactionLogBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='User IP Address')),
                ('event_message', models.CharField(blank=True, max_length=255, verbose_name='Event Message')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Metadata')),
                ('entity_type', models.CharField(blank=True, max_length=20, verbose_name='Entity Type')),
                ('entity_id', models.CharField(blank=True, max_length=100, verbose_name='Entity ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_logs', to='audit.eventtypes', verbose_name='Event Type')),
                ('status', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.PROTECT, to='base.status', verbose_name='Status')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'transaction_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('sms', 'SMS'), ('email', 'Email')], default='in_app', max_length=20, verbose_name='Channel')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read at')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('transaction_log', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='audit.transactionlogbase')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transactionlogbase',
            index=models.Index(fields=['entity_type', 'entity_id'], name='transaction_entity__b4020c_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlogbase',
            index=models.Index(fields=['triggered_by'], name='transaction_trigger_d2b13d_idx'),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['is_read', 'recipient', 'transaction_log'], name='notificatio_is_read_b703c9_idx'),
        ),
    ]
