# Generated by Django 6.0.2 on 2026-02-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactionlogbase',
            options={'ordering': ['-created_at'], 'verbose_name': 'TransactionLog', 'verbose_name_plural': 'TransactionLogs'},
        ),
        migrations.AlterModelTable(
            name='eventcategory',
            table='event_category',
        ),
        migrations.AlterModelTable(
            name='eventtypes',
            table='event_types',
        ),
    ]
