# Generated by Django 6.0.2 on 2026-02-17 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_transactionlogbase_options_and_more'),
        ('base', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtypes',
            name='event_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_types', to='base.category', verbose_name='Event Category'),
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
    ]
