# Generated by Django 6.0.2 on 2026-02-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_eventtypes_event_category_delete_eventcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlogbase',
            name='entity_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Entity Type'),
        ),
    ]
