# Generated by Django 6.0.2 on 2026-02-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_transactionlogbase_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtypes',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Code'),
        ),
    ]
