# Generated by Django 6.0.2 on 2026-02-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_eventtypes_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtypes',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Code'),
        ),
    ]
