# Generated by Django 6.0.2 on 2026-02-17 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='status',
            table='status',
        ),
    ]
